/**
 * Tokens de inyección de dependencias del módulo `catalog` (MSF-CAT-002, MSF-CAT-003).
 */
export const CATALOG_TOKENS = {
  // Puertos de salida (adapters)
  CATEGORY_REPOSITORY: 'CATALOG_CATEGORY_REPOSITORY',
  PRODUCT_REPOSITORY: 'CATALOG_PRODUCT_REPOSITORY',
  BANNER_REPOSITORY: 'CATALOG_BANNER_REPOSITORY',
  CATALOG_IDEMPOTENCY: 'CATALOG_IDEMPOTENCY',
  ACTOR_LOOKUP: 'CATALOG_ACTOR_LOOKUP',
  STOCK_ADJUSTMENT_REPOSITORY: 'CATALOG_STOCK_ADJUSTMENT_REPOSITORY',
  STOCK_ADJUSTMENT_PRODUCT_LOCK: 'CATALOG_STOCK_ADJUSTMENT_PRODUCT_LOCK',
} as const;
