/**
 * Tokens de inyección de dependencias del módulo `cart-reservation`.
 */
export const CART_TOKENS = {
  // Puertos de salida
  CART_REPOSITORY: 'CART_CART_REPOSITORY',
  STOCK_RESERVATION: 'CART_STOCK_RESERVATION',
  PRODUCT_LOOKUP: 'CART_PRODUCT_LOOKUP',
  SESSION_LOOKUP: 'CART_SESSION_LOOKUP',
  CLOCK: 'CART_CLOCK',
  IDEMPOTENCY: 'CART_IDEMPOTENCY',
  UNIT_OF_WORK: 'CART_UNIT_OF_WORK',
  REAPER: 'CART_REAPER',
  REAPER_METRICS: 'CART_REAPER_METRICS',
  TRANSITION_GUEST_TO_ADMIN: 'CART_TRANSITION_GUEST_TO_ADMIN',

  // Casos de uso
  GET_CART_USE_CASE: 'CART_GET_CART_USE_CASE',
  ADD_CART_ITEM_USE_CASE: 'CART_ADD_CART_ITEM_USE_CASE',
  SET_CART_ITEM_QUANTITY_USE_CASE: 'CART_SET_CART_ITEM_QUANTITY_USE_CASE',
  REMOVE_CART_ITEM_USE_CASE: 'CART_REMOVE_CART_ITEM_USE_CASE',
  EXPIRE_CART_RESERVATIONS_USE_CASE: 'CART_EXPIRE_CART_RESERVATIONS_USE_CASE',
  TRANSITION_GUEST_TO_ADMIN_USE_CASE:
    'CART_TRANSITION_GUEST_TO_ADMIN_USE_CASE',

  // Configuración
  REAPER_SCHEDULE_CONFIG: 'CART_REAPER_SCHEDULE_CONFIG',
} as const;
