/**
 * Mapa de trazabilidad operationId → contrato OpenAPI (MSF-API-003).
 *
 * Permite verificar que cada DTO/schema del contrato es consumido por una
 * operación concreta y que no se añaden endpoints/códigos/campos fuera del
 * contrato. Este mapa es derivado de `docs/api/openapi.yaml` y NO lo modifica.
 *
 * Este archivo es TypeScript puro (sin NestJS/Prisma/HTTP).
 */

import type {
  AdminActivationRequest,
  AdminUserProvisionResponse,
  BannerResponse,
  BannerWriteRequest,
  CartItemMutationRequest,
  CartResponse,
  CategoryResponse,
  CategoryWriteRequest,
  CheckoutResponse,
  CreateAdminUserRequest,
  CreateCheckoutRequest,
  CreateUploadUrlRequest,
  LoginRequest,
  OrderResponse,
  PagedOrderResponse,
  PagedProductResponse,
  PasswordChangeRequest,
  PasswordResetConfirmRequest,
  PasswordResetRequest,
  ProductResponse,
  ProductUpdateRequest,
  ProductWriteRequest,
  ProviderWebhookPayload,
  RegisterRequest,
  SessionResponse,
  SetCartItemQuantityRequest,
  StockAdjustmentRequest,
  StockAdjustmentResponse,
  UpdateProfileRequest,
  UploadUrlResponse,
  UserResponse,
} from './schemas';

/** Métodos HTTP soportados por el contrato. */
export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';

/** Contrato de una operación OpenAPI. */
export interface OperationContract {
  readonly operationId: string;
  readonly method: HttpMethod;
  readonly path: string;
  readonly tags: readonly string[];
  /** `true` si la operación requiere autenticación (bearer/cookie). */
  readonly authenticated: boolean;
  /** Nombre del schema de request, si existe. */
  readonly requestSchema?: string;
  /** Nombre del schema de respuesta 2xx, si existe. */
  readonly responseSchema?: string;
  /** Status de éxito (2xx). */
  readonly successStatus: number;
  /** Status de error declarados. */
  readonly errorStatuses: readonly number[];
  /** `true` si requiere el header `Idempotency-Key`. */
  readonly idempotencyKey: boolean;
  /** `true` si requiere el header `If-Match`. */
  readonly ifMatch: boolean;
}

/** Catálogo de operaciones del contrato (derivado de OpenAPI). */
export const OPERATIONS: readonly OperationContract[] = [
  {
    operationId: 'registerCustomer',
    method: 'POST',
    path: '/auth/register',
    tags: ['Auth'],
    authenticated: false,
    requestSchema: 'RegisterRequest',
    responseSchema: 'SessionResponse',
    successStatus: 201,
    errorStatuses: [400, 409, 429, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'login',
    method: 'POST',
    path: '/auth/login',
    tags: ['Auth'],
    authenticated: false,
    requestSchema: 'LoginRequest',
    responseSchema: 'SessionResponse',
    successStatus: 200,
    errorStatuses: [400, 401, 429, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'refreshSession',
    method: 'POST',
    path: '/auth/refresh',
    tags: ['Auth'],
    authenticated: false,
    responseSchema: 'SessionResponse',
    successStatus: 200,
    errorStatuses: [401, 403, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'logout',
    method: 'POST',
    path: '/auth/logout',
    tags: ['Auth'],
    authenticated: true,
    successStatus: 204,
    errorStatuses: [401, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'requestPasswordReset',
    method: 'POST',
    path: '/auth/password-reset-requests',
    tags: ['Auth'],
    authenticated: false,
    requestSchema: 'PasswordResetRequest',
    successStatus: 202,
    errorStatuses: [400, 429, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'resetPassword',
    method: 'POST',
    path: '/auth/password-resets',
    tags: ['Auth'],
    authenticated: false,
    requestSchema: 'PasswordResetConfirmRequest',
    successStatus: 204,
    errorStatuses: [400, 429, 422, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'changePassword',
    method: 'POST',
    path: '/auth/password-change',
    tags: ['Auth'],
    authenticated: true,
    requestSchema: 'PasswordChangeRequest',
    successStatus: 204,
    errorStatuses: [400, 401, 403, 409, 422, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'activateAdmin',
    method: 'POST',
    path: '/auth/admin-activations',
    tags: ['Auth'],
    authenticated: false,
    requestSchema: 'AdminActivationRequest',
    successStatus: 204,
    errorStatuses: [400, 429, 422, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'getMyProfile',
    method: 'GET',
    path: '/me',
    tags: ['Profile'],
    authenticated: true,
    responseSchema: 'UserResponse',
    successStatus: 200,
    errorStatuses: [401, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'updateMyProfile',
    method: 'PATCH',
    path: '/me',
    tags: ['Profile'],
    authenticated: true,
    requestSchema: 'UpdateProfileRequest',
    responseSchema: 'UserResponse',
    successStatus: 200,
    errorStatuses: [400, 401, 403, 409, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'listCategories',
    method: 'GET',
    path: '/categories',
    tags: ['Catalog'],
    authenticated: false,
    responseSchema: 'CategoryResponse[]',
    successStatus: 200,
    errorStatuses: [500, 429],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'listProducts',
    method: 'GET',
    path: '/products',
    tags: ['Catalog'],
    authenticated: false,
    responseSchema: 'PagedProductResponse',
    successStatus: 200,
    errorStatuses: [400, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'getProduct',
    method: 'GET',
    path: '/products/{productId}',
    tags: ['Catalog'],
    authenticated: false,
    responseSchema: 'ProductResponse',
    successStatus: 200,
    errorStatuses: [404, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'listActiveBanners',
    method: 'GET',
    path: '/banners',
    tags: ['Catalog'],
    authenticated: false,
    responseSchema: 'BannerResponse[]',
    successStatus: 200,
    errorStatuses: [500, 429],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'getCart',
    method: 'GET',
    path: '/cart',
    tags: ['Cart'],
    authenticated: true,
    responseSchema: 'CartResponse',
    successStatus: 200,
    errorStatuses: [401, 403, 410, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'addCartItem',
    method: 'POST',
    path: '/cart/items',
    tags: ['Cart'],
    authenticated: true,
    requestSchema: 'CartItemMutationRequest',
    responseSchema: 'CartResponse',
    successStatus: 201,
    errorStatuses: [400, 403, 409, 410, 422, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'setCartItemQuantity',
    method: 'PUT',
    path: '/cart/items/{productId}',
    tags: ['Cart'],
    authenticated: true,
    requestSchema: 'SetCartItemQuantityRequest',
    responseSchema: 'CartResponse',
    successStatus: 200,
    errorStatuses: [400, 401, 403, 404, 409, 410, 422, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'removeCartItem',
    method: 'DELETE',
    path: '/cart/items/{productId}',
    tags: ['Cart'],
    authenticated: true,
    successStatus: 204,
    errorStatuses: [401, 403, 404, 409, 410, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'createCheckout',
    method: 'POST',
    path: '/checkouts',
    tags: ['Checkout'],
    authenticated: true,
    requestSchema: 'CreateCheckoutRequest',
    responseSchema: 'CheckoutResponse',
    successStatus: 201,
    errorStatuses: [400, 401, 403, 409, 422, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'listMyOrders',
    method: 'GET',
    path: '/orders',
    tags: ['Orders'],
    authenticated: true,
    responseSchema: 'PagedOrderResponse',
    successStatus: 200,
    errorStatuses: [401, 403, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'getMyOrder',
    method: 'GET',
    path: '/orders/{orderId}',
    tags: ['Orders'],
    authenticated: true,
    responseSchema: 'OrderResponse',
    successStatus: 200,
    errorStatuses: [401, 403, 404, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'provisionAdminUser',
    method: 'POST',
    path: '/admin/users',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'CreateAdminUserRequest',
    responseSchema: 'AdminUserProvisionResponse',
    successStatus: 201,
    errorStatuses: [400, 401, 403, 404, 409, 429, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminListCategories',
    method: 'GET',
    path: '/admin/categories',
    tags: ['Admin'],
    authenticated: true,
    responseSchema: 'CategoryResponse[]',
    successStatus: 200,
    errorStatuses: [401, 403, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'adminCreateCategory',
    method: 'POST',
    path: '/admin/categories',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'CategoryWriteRequest',
    responseSchema: 'CategoryResponse',
    successStatus: 201,
    errorStatuses: [400, 401, 403, 409, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminUpdateCategory',
    method: 'PATCH',
    path: '/admin/categories/{categoryId}',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'CategoryWriteRequest',
    responseSchema: 'CategoryResponse',
    successStatus: 200,
    errorStatuses: [400, 401, 403, 404, 409, 500],
    idempotencyKey: true,
    ifMatch: true,
  },
  {
    operationId: 'adminDeleteCategory',
    method: 'DELETE',
    path: '/admin/categories/{categoryId}',
    tags: ['Admin'],
    authenticated: true,
    successStatus: 204,
    errorStatuses: [401, 403, 404, 409, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminListProducts',
    method: 'GET',
    path: '/admin/products',
    tags: ['Admin'],
    authenticated: true,
    responseSchema: 'PagedProductResponse',
    successStatus: 200,
    errorStatuses: [401, 403, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'adminCreateProduct',
    method: 'POST',
    path: '/admin/products',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'ProductWriteRequest',
    responseSchema: 'ProductResponse',
    successStatus: 201,
    errorStatuses: [400, 401, 403, 409, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminUpdateProduct',
    method: 'PATCH',
    path: '/admin/products/{productId}',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'ProductUpdateRequest',
    responseSchema: 'ProductResponse',
    successStatus: 200,
    errorStatuses: [400, 401, 403, 404, 409, 500],
    idempotencyKey: true,
    ifMatch: true,
  },
  {
    operationId: 'adminDeleteProduct',
    method: 'DELETE',
    path: '/admin/products/{productId}',
    tags: ['Admin'],
    authenticated: true,
    successStatus: 204,
    errorStatuses: [401, 403, 404, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminCreateProductStockAdjustment',
    method: 'POST',
    path: '/admin/products/{productId}/stock-adjustments',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'StockAdjustmentRequest',
    responseSchema: 'StockAdjustmentResponse',
    successStatus: 201,
    errorStatuses: [400, 401, 403, 404, 409, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminListBanners',
    method: 'GET',
    path: '/admin/banners',
    tags: ['Admin'],
    authenticated: true,
    responseSchema: 'BannerResponse[]',
    successStatus: 200,
    errorStatuses: [401, 403, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'adminCreateBanner',
    method: 'POST',
    path: '/admin/banners',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'BannerWriteRequest',
    responseSchema: 'BannerResponse',
    successStatus: 201,
    errorStatuses: [400, 401, 403, 409, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminUpdateBanner',
    method: 'PATCH',
    path: '/admin/banners/{bannerId}',
    tags: ['Admin'],
    authenticated: true,
    requestSchema: 'BannerWriteRequest',
    responseSchema: 'BannerResponse',
    successStatus: 200,
    errorStatuses: [400, 401, 403, 404, 409, 500],
    idempotencyKey: true,
    ifMatch: true,
  },
  {
    operationId: 'adminDeleteBanner',
    method: 'DELETE',
    path: '/admin/banners/{bannerId}',
    tags: ['Admin'],
    authenticated: true,
    successStatus: 204,
    errorStatuses: [401, 403, 404, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'adminListOrders',
    method: 'GET',
    path: '/admin/orders',
    tags: ['Admin'],
    authenticated: true,
    responseSchema: 'PagedOrderResponse',
    successStatus: 200,
    errorStatuses: [401, 403, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'adminGetOrder',
    method: 'GET',
    path: '/admin/orders/{orderId}',
    tags: ['Admin'],
    authenticated: true,
    responseSchema: 'OrderResponse',
    successStatus: 200,
    errorStatuses: [401, 403, 404, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'createMediaUploadUrl',
    method: 'POST',
    path: '/media/upload-urls',
    tags: ['Media'],
    authenticated: true,
    requestSchema: 'CreateUploadUrlRequest',
    responseSchema: 'UploadUrlResponse',
    successStatus: 201,
    errorStatuses: [400, 401, 403, 500],
    idempotencyKey: true,
    ifMatch: false,
  },
  {
    operationId: 'receiveWompiWebhook',
    method: 'POST',
    path: '/webhooks/wompi',
    tags: ['Webhooks'],
    authenticated: false,
    requestSchema: 'ProviderWebhookPayload',
    successStatus: 204,
    errorStatuses: [400, 401, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
  {
    operationId: 'receiveMercadoPagoWebhook',
    method: 'POST',
    path: '/webhooks/mercado-pago',
    tags: ['Webhooks'],
    authenticated: false,
    requestSchema: 'ProviderWebhookPayload',
    successStatus: 204,
    errorStatuses: [400, 401, 500],
    idempotencyKey: false,
    ifMatch: false,
  },
];

/** Busca el contrato de una operación por `operationId`. */
export function findOperation(
  operationId: string,
): OperationContract | undefined {
  return OPERATIONS.find((op) => op.operationId === operationId);
}

/** Re-export de tipos de schemas usados por el mapa. */
export type {
  AdminActivationRequest,
  AdminUserProvisionResponse,
  BannerResponse,
  BannerWriteRequest,
  CartItemMutationRequest,
  CartResponse,
  CategoryResponse,
  CategoryWriteRequest,
  CheckoutResponse,
  CreateAdminUserRequest,
  CreateCheckoutRequest,
  CreateUploadUrlRequest,
  LoginRequest,
  OrderResponse,
  PagedOrderResponse,
  PagedProductResponse,
  PasswordChangeRequest,
  PasswordResetConfirmRequest,
  PasswordResetRequest,
  ProductResponse,
  ProductUpdateRequest,
  ProductWriteRequest,
  ProviderWebhookPayload,
  RegisterRequest,
  SessionResponse,
  SetCartItemQuantityRequest,
  StockAdjustmentRequest,
  StockAdjustmentResponse,
  UpdateProfileRequest,
  UploadUrlResponse,
  UserResponse,
};
