/**
 * Tokens de inyección de dependencias del módulo `payments` (MSF-PAY-002 / MSF-PAY-003 / MSF-PAY-004).
 */
export const PAYMENTS_TOKENS = {
  // Puertos de salida
  PAYMENT_PROVIDER: 'PAYMENT_PROVIDER',
  PAYMENT_REPOSITORY: 'PAYMENT_REPOSITORY',

  // Estrategias de proveedor
  PAYMENT_PROVIDER_WOMPI: 'PAYMENT_PROVIDER_WOMPI',
  PAYMENT_PROVIDER_MERCADO_PAGO: 'PAYMENT_PROVIDER_MERCADO_PAGO',

  // Selector de estrategia
  PAYMENT_PROVIDER_SELECTOR: 'PAYMENT_PROVIDER_SELECTOR',

  // Configuración
  PAYMENT_CONFIG_WOMPI: 'PAYMENT_CONFIG_WOMPI',
  PAYMENT_CONFIG_MERCADO_PAGO: 'PAYMENT_CONFIG_MERCADO_PAGO',

  // Firma de webhooks (MSF-PAY-003)
  WOMPI_WEBHOOK_SIGNATURE: 'PAYMENTS_WOMPI_WEBHOOK_SIGNATURE',
  MERCADO_PAGO_WEBHOOK_SIGNATURE: 'PAYMENTS_MERCADO_PAGO_WEBHOOK_SIGNATURE',

  // Repositorio de eventos de webhook (MSF-PAY-003)
  WEBHOOK_EVENT_REPOSITORY: 'PAYMENTS_WEBHOOK_EVENT_REPOSITORY',

  // Unidad de trabajo de webhook (MSF-PAY-003)
  PROCESS_WEBHOOK_UNIT_OF_WORK: 'PAYMENTS_PROCESS_WEBHOOK_UNIT_OF_WORK',

  // Reconciliación (MSF-PAY-004)
  PAYMENT_RECONCILIATION_REPOSITORY: 'PAYMENTS_RECONCILIATION_REPOSITORY',
  PAYMENT_RECONCILIATION_METRICS: 'PAYMENTS_RECONCILIATION_METRICS',
  PAYMENT_RECONCILIATION_SCHEDULE_CONFIG:
    'PAYMENTS_RECONCILIATION_SCHEDULE_CONFIG',

  // Casos de uso
  CREATE_PAYMENT_USE_CASE: 'PAYMENTS_CREATE_PAYMENT_USE_CASE',
  PROCESS_WEBHOOK_USE_CASE: 'PAYMENTS_PROCESS_WEBHOOK_USE_CASE',
  RECONCILE_PENDING_PAYMENTS_USE_CASE:
    'PAYMENTS_RECONCILE_PENDING_PAYMENTS_USE_CASE',
} as const;
