/**
 * Tokens de inyección de dependencias del módulo `identity`.
 *
 * NestJS no permite usar interfaces TypeScript como tokens de inyección
 * (no existen en runtime). Estos strings constantes permiten que el
 * contenedor DI resuelva las dependencias por nombre.
 */
export const IDENTITY_TOKENS = {
  USER_REPOSITORY: 'IDENTITY_USER_REPOSITORY',
  SESSION_REPOSITORY: 'IDENTITY_SESSION_REPOSITORY',
  PASSWORD_HASHER: 'IDENTITY_PASSWORD_HASHER',
  JWT: 'IDENTITY_JWT',
  COOKIE_TOKEN: 'IDENTITY_COOKIE_TOKEN',
  CLOCK: 'IDENTITY_CLOCK',
  CART_RESERVATION: 'IDENTITY_CART_RESERVATION',
  ADMIN_ACTIVATION_TOKEN_REPOSITORY: 'IDENTITY_ADMIN_ACTIVATION_TOKEN_REPOSITORY',
  IDEMPOTENCY: 'IDENTITY_IDEMPOTENCY',
  PROVISION_UNIT_OF_WORK: 'IDENTITY_PROVISION_UNIT_OF_WORK',
  IDEMPOTENCY_PURGE_REPOSITORY: 'IDENTITY_IDEMPOTENCY_PURGE_REPOSITORY',
  IDEMPOTENCY_SCOPE_EVALUATOR: 'IDENTITY_IDEMPOTENCY_SCOPE_EVALUATOR',
  PURGE_METRICS: 'IDENTITY_PURGE_METRICS',
  PURGE_LOGGER: 'IDENTITY_PURGE_LOGGER',
  PURGE_SCHEDULE_CONFIG: 'IDENTITY_PURGE_SCHEDULE_CONFIG',
  INITIAL_ADMIN_SECRET: 'IDENTITY_INITIAL_ADMIN_SECRET',
  BOOTSTRAP_UNIT_OF_WORK: 'IDENTITY_BOOTSTRAP_UNIT_OF_WORK',
  ACTIVATE_ADMIN_UNIT_OF_WORK: 'IDENTITY_ACTIVATE_ADMIN_UNIT_OF_WORK',
  CHANGE_PASSWORD_UNIT_OF_WORK: 'IDENTITY_CHANGE_PASSWORD_UNIT_OF_WORK',
  UPDATE_PROFILE_UNIT_OF_WORK: 'IDENTITY_UPDATE_PROFILE_UNIT_OF_WORK',
  PASSWORD_RESET_TOKEN_REPOSITORY: 'IDENTITY_PASSWORD_RESET_TOKEN_REPOSITORY',
  EMAIL: 'IDENTITY_EMAIL',
  RESET_PASSWORD_UNIT_OF_WORK: 'IDENTITY_RESET_PASSWORD_UNIT_OF_WORK',
  REQUEST_PASSWORD_RESET_UNIT_OF_WORK: 'IDENTITY_REQUEST_PASSWORD_RESET_UNIT_OF_WORK',

  // Use cases (MSF-ID-003)
  REGISTER_USE_CASE: 'IDENTITY_REGISTER_USE_CASE',
  GET_MY_PROFILE_USE_CASE: 'IDENTITY_GET_MY_PROFILE_USE_CASE',
  UPDATE_PROFILE_USE_CASE: 'IDENTITY_UPDATE_PROFILE_USE_CASE',
  CHANGE_PASSWORD_USE_CASE: 'IDENTITY_CHANGE_PASSWORD_USE_CASE',
  REQUEST_PASSWORD_RESET_USE_CASE: 'IDENTITY_REQUEST_PASSWORD_RESET_USE_CASE',
  RESET_PASSWORD_USE_CASE: 'IDENTITY_RESET_PASSWORD_USE_CASE',
  LOGIN_USE_CASE: 'IDENTITY_LOGIN_USE_CASE',
  REFRESH_SESSION_USE_CASE: 'IDENTITY_REFRESH_SESSION_USE_CASE',
  LOGOUT_USE_CASE: 'IDENTITY_LOGOUT_USE_CASE',

  // Configuración (MSF-ID-003)
  REFRESH_COOKIE_TTL_MS: 'IDENTITY_REFRESH_COOKIE_TTL_MS',
  PROVISION_ACTIVATION_TOKEN_TTL_MS: 'IDENTITY_PROVISION_ACTIVATION_TOKEN_TTL_MS',
} as const;
